name: Build image

on:
  push:
    branches: ["main"]
    tags:
      - 'v*.*.*' # glob for semver tags (including prereleases)
  pull_request:
    branches: [main]

jobs:
  call-build-image:
    uses: osg-htc/build-push/.github/workflows/build-push.yaml@34bb494bf3c926aafcd210c4eecb1e6088fc65f2 # main as of 2025-03-12
    secrets: inherit
    with:
      image: 'hub.opensciencegrid.org/opensciencegrid/topology-v2'
